### ISSUE TITLE
App sometimes (?) crashes with API 23 and higher

### ISSUE THREAD

**Issue by leletec** [leletec/NameMemo#12]
With API 23 the app crashes on the first start, telling you that the table "settings" does not exist, although it has been inizialised before.
This does not happen with API 22.

**Comment by leletec** [comment]
Also crashes with API 24

**Comment by leletec** [comment]
Error is gone...wait what?!

**Comment by okitec** [comment]
You might want to remove the high-prio label as well.

**Comment by leletec** [comment]
It's back... :sob: 
...this time for the pictures table.

**Comment by leletec** [comment]
E/SQLiteLog: (1) no such table: pictures
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.leletec.namememo, PID: 3659
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{de.leletec.namememo/main.MainActivity}: android.database.sqlite.SQLiteException: no such table: pictures (code 1): , while compiling: SELECT \* FROM pictures
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: android.database.sqlite.SQLiteException: no such table: pictures (code 1): , while compiling: SELECT \* FROM pictures
                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                      at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                      at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                      at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                      at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                      at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                      at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
                      at database.PicturesDAO.getAllPics(PicturesDAO.java:100)
                      at main.MainActivity.loadPictures(MainActivity.java:352)
                      at main.MainActivity.onCreate(MainActivity.java:116)
                      at android.app.Activity.performCreate(Activity.java:6664)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
Application terminated.

**Comment by leletec** [comment]
Aand it's gone after a reinstallation...

**Comment by leletec** [comment]
Appears to be a faulty database, caused by Android.
